import { FieldValue, Timestamp, type DocumentData } from "firebase-admin/firestore";
import { db, shouldUseLocalAuthStore } from "../../firebase/server";
import * as local from "./localRiskReportsStore";
import type { RiskReport } from "../../services/map/mapTypes";

function timestampToDate(value: unknown): Date {
  if (value instanceof Timestamp) {
    return value.toDate();
  }
  if (
    typeof value === "object" &&
    value !== null &&
    "_seconds" in value &&
    typeof (value as { _seconds: unknown })._seconds === "number"
  ) {
    return new Date((value as { _seconds: number })._seconds * 1000);
  }
  if (typeof value === "string") return new Date(value);
  return new Date();
}

function mapDoc(id: string, data: DocumentData): RiskReport {
  return {
    id,
    userId: String(data.userId ?? ""),
    location: String(data.location ?? ""),
    latitude: Number(data.latitude ?? 0),
    longitude: Number(data.longitude ?? 0),
    rainfall: Number(data.rainfall ?? 0),
    temperature: Number(data.temperature ?? 0),
    floodRisk: Number(data.floodRisk ?? 0),
    droughtRisk: Number(data.droughtRisk ?? 0),
    cropSuitability: Number(data.cropSuitability ?? 0),
    recommendation: String(data.recommendation ?? ""),
    timestamp: timestampToDate(data.timestamp),
  };
}

/**
 * Creates a new risk report document in Firestore (or local database fallback).
 */
export async function createRiskReportDocument(input: Omit<RiskReport, "id" | "timestamp">): Promise<string> {
  const userId = input.userId.trim().toLowerCase();
  if (shouldUseLocalAuthStore()) {
    return local.localCreateRiskReport({
      ...input,
      timestamp: new Date(),
    });
  }

  const col = db.collection("riskReports");
  const ref = col.doc();
  const payload = {
    id: ref.id,
    userId,
    location: input.location.trim(),
    latitude: input.latitude,
    longitude: input.longitude,
    rainfall: input.rainfall,
    temperature: input.temperature,
    floodRisk: input.floodRisk,
    droughtRisk: input.droughtRisk,
    cropSuitability: input.cropSuitability,
    recommendation: input.recommendation,
    timestamp: FieldValue.serverTimestamp(),
  };

  await ref.set(payload);
  return ref.id;
}

/**
 * Lists the latest risk reports generated by a specific user.
 */
export async function listRiskReports(userId: string, max = 20): Promise<RiskReport[]> {
  const cleanId = userId.trim().toLowerCase();
  if (!cleanId) return [];

  if (shouldUseLocalAuthStore()) {
    return local.localListRiskReports(cleanId, max);
  }

  const qs = await db
    .collection("riskReports")
    .where("userId", "==", cleanId)
    .orderBy("timestamp", "desc")
    .limit(max)
    .get();

  return qs.docs.map((doc) => mapDoc(doc.id, doc.data()));
}
